apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: pennedbyarjun.blog #change name accordingly
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8spractisebucketbyarjun/pennedbyarjun.blog #provide your S3 bucket name
  dnsZone: pennedbyarjun.blog #change to your domain name
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess: #change CIDR blocks to restrict access
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.35.3 #change to desired Kubernetes version
  masterPublicName: api.pennedbyarjun.blog #change to your domain (api.yourdomain.com)
  networkCIDR: 172.20.0.0/16 #change to your desired VPC CIDR block
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10 #change CIDR if needed for your network configuration
  sshAccess: #change CIDR blocks to restrict SSH access
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.0.0/18 #change subnet CIDR accordingly
    name: us-east-1a #change to your subnet name
    type: Public
    zone: us-east-1a #change to your availability zone
  - cidr: 172.20.64.0/18 #change subnet CIDR accordingly
    name: us-east-1b #change to your subnet name
    type: Public
    zone: us-east-1b #change to your availability zone
  - cidr: 172.20.128.0/18 #change subnet CIDR accordingly
    name: us-east-1c #change to your subnet name
    type: Public
    zone: us-east-1c #change to your availability zone
  topology:
    dns:
      type: Public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: pennedbyarjun.blog #change to your cluster name
  name: control-plane-us-east-1a #change to your instance group name
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218 #change to your desired AMI
  machineType: t3.medium #change to your desired instance type
  maxSize: 1 #change to your desired max number of instances
  minSize: 1 #change to your desired min number of instances
  role: Master
  rootVolumeSize: 15 #change to your desired root volume size in GB
  subnets:
  - us-east-1a #change to your subnet name

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: pennedbyarjun.blog #change to your cluster name
  name: nodes-us-east-1a #change to your node instance group name
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218 #change to your desired AMI
  machineType: t3.medium #change to your desired instance type
  maxSize: 1 #change to your desired max number of instances
  minSize: 1 #change to your desired min number of instances
  role: Node
  rootVolumeSize: 15 #change to your desired root volume size in GB
  subnets:
  - us-east-1a #change to your subnet name

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: pennedbyarjun.blog #change to your cluster name
  name: nodes-us-east-1b #change to your node instance group name
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218 #change to your desired AMI
  machineType: t3.medium #change to your desired instance type
  maxSize: 1 #change to your desired max number of instances
  minSize: 1 #change to your desired min number of instances
  role: Node
  rootVolumeSize: 15 #change to your desired root volume size in GB
  subnets:
  - us-east-1b #change to your subnet name

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: pennedbyarjun.blog #change to your cluster name
  name: nodes-us-east-1c #change to your node instance group name
spec:
  image: 099720109477/ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20260218 #change to your desired AMI
  machineType: t3.medium #change to your desired instance type
  maxSize: 1 #change to your desired max number of instances
  minSize: 1 #change to your desired min number of instances
  role: Node
  rootVolumeSize: 15 #change to your desired root volume size in GB
  subnets:
  - us-east-1c #change to your subnet name

---

apiVersion: kops.k8s.io/v1alpha2
kind: SSHCredential
metadata:
  labels:
    kops.k8s.io/cluster: pennedbyarjun.blog #change to your cluster name
  name: admin
spec:
  publicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPF9K7LDH7fSaXgtVVDbQm4K3nlWgfc7PZHpIfjAPpAH #change to your public SSH key
